name: Makefile CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rombp-win32
        path: .
